language: scala

os: linux
dist: xenial
sudo: required
jdk: openjdk8

before_install:
  - sudo apt-get install wget build-essential openjdk-8-jdk icedtea-8-plugin libssl-dev
  - env
  - which javac
  - sudo update-java-alternatives --list
  - java -version
  - wget -O sgx_installer.bin https://download.01.org/intel-sgx/linux-2.3.1/ubuntu16.04/sgx_linux_x64_sdk_2.3.101.46683.bin
  - chmod +x ./sgx_installer.bin
  - echo yes | ./sgx_installer.bin
  - source sgxsdk/environment
  - openssl ecparam -name prime256v1 -genkey -noout -out private_key.pem
  - export SPARKSGX_DATA_DIR=$PWD/data
  - export PRIVATE_KEY_PATH=$PWD/private_key.pem

script: sbt -Dspark.ui.showConsoleProgress=false 'set ivyLoggingLevel := UpdateLogging.Quiet' test
